### ISSUE TITLE
Contact information is missing

### ISSUE THREAD

**Issue by zigazajc007** [seirdotexe/chacha20#1]
Hello,

I can't find any way to contact you. Do you have a matrix account, public email, discord or any other way for me to contact you?

Best regards,
Ziga

**Comment by seirdotexe** [comment]
Hello Ziga,

I'm sending you this to let you know that I'm alive! I'll get back to you about this today.

**Comment by seirdotexe** [comment]
Hello Ziga,

You can contact me on seirdotexe@gmail.com.
